version: '1.0.0.{build}'
image: Ubuntu
init:
  tzutil /s "UTC"
services:
  - docker
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
  - date +'%:z %Z'
  - dotnet build TestEnvironment.sln -c Release
test_script:
  - dotnet test ./test/TestEnvironment.Docker.Tests/TestEnvironment.Docker.Tests.csproj -c Release
artifacts:
  - path: '**\*.nupkg'